### ISSUE TITLE
@cache_response cannot cache HttpResponse

### ISSUE THREAD

**Issue by anka-sirota** [chibisov/drf-extensions#129]
If view returns a normal HttpResponse object, cache_response decorator fails with an AttiributeError trying to call a render() on it:

```
Traceback (most recent call last):
  File "/home/anna/supervisor/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/anna/supervisor/.venv/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/anna/supervisor/.venv/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/anna/supervisor/.venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 455, in dispatch
    response = self.handle_exception(exc)
  File "/home/anna/supervisor/.venv/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/anna/supervisor/.venv/local/lib/python2.7/site-packages/rest_framework_extensions/cache/decorators.py", line 43, in inner
    kwargs=kwargs,
  File "/home/anna/supervisor/.venv/local/lib/python2.7/site-packages/rest_framework_extensions/cache/decorators.py", line 64, in process_cache_response
    response.render()  # should be rendered, before picklining while storing to cache
AttributeError: 'HttpResponse' object has no attribute 'render'
```

According to [DRF documentation](http://www.django-rest-framework.org/api-guide/responses/), views are not obliged to return a Response object, so checking if it is indeed a Response object and needs to be rendered should fix the issue

**Comment by auvipy** [comment]
any work around to fix it?

**Comment by auvipy** [comment]
as drf-ext is intend to b used with drf, it is designed to be used with drf Response not django HttpResponse
