### ISSUE TITLE
[Django 2.0] TypeError: 'bool' object is not callable 

### ISSUE THREAD

**Issue by mbaragiola** [chibisov/drf-extensions#200]
Hello, getting this error with Django 2.0, Python 3.6.3 and `master` branch of `drf-extensions`:

```
Traceback (most recent call last):
  File "/app/users/v1/tests/tests.py", line 278, in test_update
    response = self.client.get(url)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 291, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 208, in get
    return self.generic('GET', path, **r)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 237, in generic
    method, path, data, content_type, secure, **extra)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 404, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 288, in request
    return super(APIClient, self).request(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/test.py", line 240, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/test/client.py", line 485, in request
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/cache/decorators.py", line 48, in inner
    kwargs=kwargs,
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/cache/decorators.py", line 63, in process_cache_response
    kwargs=kwargs
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/cache/decorators.py", line 94, in calculate_key
    kwargs=kwargs,
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/key_constructor/constructors.py", line 30, in __call__
    return self.get_key(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/key_constructor/constructors.py", line 50, in get_key
    kwargs=kwargs
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/key_constructor/constructors.py", line 74, in _get_key
    self.get_data_from_bits(**_kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/key_constructor/constructors.py", line 90, in get_data_from_bits
    result_dict[bit_name] = bit_instance.get_data(params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework_extensions/key_constructor/bits.py", line 119, in get_data
    if hasattr(request, 'user') and request.user and request.user.is_authenticated():
TypeError: 'bool' object is not callable
```

As you can see, I am using your cache solution with UserKeyBit as one of the bits.

I haven't found any change relevant on the [Django 2.0 release notes](https://docs.djangoproject.com/en/2.0/releases/2.0/), so that's why I'm posting this as an issue instead of a PR with a solution. But I can volunteer to provide one if needed. Thanks for this amazing project!

**Comment by David-OConnor** [comment]
Per that page: "Using User.is_authenticated() and User.is_anonymous() as methods rather than properties is no longer supported."

**Comment by auvipy** [comment]
yes plz send a pr if possible

**Comment by T-101** [comment]
in dal/views.py, would this be satisfactory?

    def has_add_permission(self, request):
        """Return True if the user has the permission to add a model."""
        try:
            user_is_authenticated = request.user.is_authenticated()
        except TypeError:
            user_is_authenticated = request.user.is_authenticated
        
        if not user_is_authenticated:
            return False

This approach would retain backwards compatibility

**Comment by auvipy** [comment]
yes

**Comment by T-101** [comment]
Upstream problem then. I'll see if the latest DAL 3.3.0-rc5 has this issue fixed. If not, I'll PR to there

**Comment by auvipy** [comment]
latest version of django change this

**Comment by tural-esger** [comment]
@David-OConnor you saved my day! Thank you!

**Comment by auvipy** [comment]
https://github.com/chibisov/drf-extensions/pull/209 more fixes plz review

**Comment by chugunovyar** [comment]
from django.contrib.auth.mixins import LoginRequiredMixin

help me
