### ISSUE TITLE
[windows] [tests]: No module named 'settings'

### ISSUE THREAD

**Issue by thesunlover** [chibisov/drf-extensions#225]
python version 3.6

```
django.2.0 runtests: commands[0] | F:\drf-extensions\.tox\django.2.0\Scripts/django-admin.py test --settings=settings tests_app --verbosity=3
Traceback (most recent call last):
  File "F:\drf-extensions\.tox\django.2.0\Scripts/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "F:\drf-extensions\.tox\django.2.0\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "F:\drf-extensions\.tox\django.2.0\lib\site-packages\django\core\management\__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "F:\drf-extensions\.tox\django.2.0\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "F:\drf-extensions\.tox\django.2.0\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "F:\drf-extensions\.tox\django.2.0\lib\site-packages\django\conf\__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "F:\drf-extensions\.tox\django.2.0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'
ERROR: InvocationError for command 'F:\\drf-extensions\\.tox\\django.2.0\\Scripts/django-admin.py test --settings=settings tests_app --verbosity=3' (exited with code 1)
______________________________________________________ summary _______________________________________________________
ERROR:   django.2.0: commands failed


PS F:\drf-extensions> pip list
Package             Version
------------------- -------
djangorestframework 3.8.2
drf-extensions      0.3.1
pip                 10.0.1
pluggy              0.6.0
py                  1.5.3
setuptools          39.0.1
six                 1.11.0
tox                 3.0.0
virtualenv          16.0.0
```

**Comment by auvipy** [comment]
could you try the latest release?

**Comment by thesunlover** [comment]
sorry for late response:
here is what I got when I try to recreate the tox env

django.2.0 runtests: commands[0] | 'D:\drf-extensions-master\.tox\django.2.0\Scripts/django-admin.py' test --settings=settings tests_app
Traceback (most recent call last):
  File "D:\drf-extensions-master\.tox\django.2.0\Scripts/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "D:\drf-extensions-master\.tox\django.2.0\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "D:\drf-extensions-master\.tox\django.2.0\lib\site-packages\django\core\management\__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "D:\drf-extensions-master\.tox\django.2.0\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "D:\drf-extensions-master\.tox\django.2.0\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\drf-extensions-master\.tox\django.2.0\lib\site-packages\django\conf\__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "D:\drf-extensions-master\.tox\django.2.0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'
ERROR: InvocationError for command 'D:\\drf-extensions-master\\.tox\\django.2.0\\Scripts/django-admin.py test --settings=settings tests_app' (exited with code 1)

**Comment by thesunlover** [comment]
probably tox cannot find the path to the settings.py I suppose...

**Comment by OskarPersson** [comment]
I'm getting the same error on my Windows machine. To solve this specific error you have to update `setenv` with the following entry:

```
PYTHONPATH = {toxinidir}{:}{toxinidir}/tests_app
```

See the documentation for `{:}` here: https://tox.readthedocs.io/en/latest/config.html#globally-available-substitutions

Though after this change I'm getting another error instead:
```
ERROR: test suite for <class 'tests_app.tests.functional.cache.decorators.tests.TestCacheResponseFunctionally'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\nose\plugins\multiprocess.py", line 788, in run
    self.setUp()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\nose\suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\nose\plugins\multiprocess.py", line 770, in setupContext
    super(NoSharedFixtureContextSuite, self).setupContext(context)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\nose\suite.py", line 316, in setupContext
    try_run(context, names)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\test\testcases.py", line 1123, in setUpClass
    super().setUpClass()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\test\testcases.py", line 197, in setUpClass
    cls._add_databases_failures()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\test\testcases.py", line 218, in _add_databases_failures
    cls.databases = cls._validate_databases()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\test\testcases.py", line 204, in _validate_databases
    if alias not in connections:
TypeError: argument of type 'ConnectionHandler' is not iterable
```

**Comment by OskarPersson** [comment]
By using the built-in test runner (remove `TEST_RUNNER` from tests_app/settings.py) you get even further:

```
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: django_nose, messages, rest_framework_extensions
  Apply all migrations: auth, contenttypes, functional, guardian, sessions, sites, unit
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying functional.0001_initial... OK
  Applying guardian.0001_initial... OK
  Applying guardian.0002_generic_permissions_index... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying unit.0001_initial... OK
Traceback (most recent call last):
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: functional_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".tox\py37-django22-drf310\Scripts\django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\management\commands\test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\management\commands\test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\test\runner.py", line 629, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\test\runner.py", line 554, in setup_databases
    self.parallel, **kwargs
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\test\utils.py", line 174, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\base\creation.py", line 80, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\base\creation.py", line 123, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\serializers\__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\core\serializers\base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\base\creation.py", line 120, in get_objects
    yield from queryset.iterator()
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\models\query.py", line 341, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\models\sql\compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\oskar\git\drf-extensions\.tox\py37-django22-drf310\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: functional_book
```

Not sure what the actual problem is here :/
