### ISSUE TITLE
Will this library still be maintained and have new versions released?

### ISSUE THREAD

**Issue by whitewhite944** [chibisov/drf-extensions#340]
I really like this library... I hope it will not be abandoned. I hope this is helpful! Let me know if you have any other questions.

**Comment by auvipy** [comment]
yes I will release a new version this week hopefully. it will never be abandoned

**Comment by fkleon** [comment]
@auvipy Any update on this in light of the imminent EOL date of Django 3.2? There are some known issues with Django 4.2 compatibility (e.g. https://github.com/chibisov/drf-extensions/issues/337#issuecomment-1598368705)

**Comment by auvipy** [comment]
I would be happy to review contributions as Im busy for a while

**Comment by whitewhite944** [comment]
@auvipy @fkleon To reduce workload, I think it is reasonable to only keep updating Django LTS versions, which can both keep up with the updates and not fall behind too much.

**Comment by auvipy** [comment]
I know but CI is broken. And time is very limited due to personal n pro setup

**Comment by naquiroz** [comment]
Hey, no releases for the past 8 months, any plans on maintining it still? Also, what happend to the autho [chibisov](https://github.com/chibisov)?

**Comment by chibisov** [comment]
> Hey, no releases for the past 8 months, any plans on maintining it still? Also, what happend to the author @chibisov ?

Hi. It's been a while since I've checked the repo.
I tried to fix the CI - and it works now. But tests are failing. E.g.:
```
======================================================================
FAIL: test_for_unsafe_methods (tests_app.tests.unit._etag.decorators.tests.ETAGProcessorTestBehavior_if_none_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/drf-extensions/drf-extensions/tests_app/tests/unit/_etag/decorators/tests.py", line 273, in test_for_unsafe_methods
    self.run_for_methods(UNSAFE_METHODS, condition_failed_status=status.HTTP_412_PRECONDITION_FAILED)
  File "/home/runner/work/drf-extensions/drf-extensions/tests_app/tests/unit/_etag/decorators/tests.py", line 204, in run_for_methods
    self.assertEqual(response.status_code, condition_failed_status, msg=msg)
AssertionError: 200 != 412 : For "POST" and if-none-match value 123 condition should fail and response must be returned with 412 status. But it is 200
```

I can release new version, but only when tests are fixed. I don't have time now, but your contribution if appreciated.

**Comment by auvipy** [comment]
I took help from a new contributor and fixed the CI, and released a new version last week.
